android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/io/rebble/fossil/BlueCommon.kt, android/app/src/main/kotlin/io/rebble/fossil/BlueIO.kt, android/app/src/main/kotlin/io/rebble/fossil/BlueSerial.kt, android/app/src/main/kotlin/io/rebble/fossil/FossilApplication.kt, android/app/src/main/kotlin/io/rebble/fossil/MainActivity.kt, android/app/src/main/kotlin/io/rebble/fossil/WatchService.kt, android/app/src/main/kotlin/io/rebble/fossil/di/AppComponent.kt, android/app/src/main/kotlin/io/rebble/fossil/di/AppModule.kt, android/app/src/main/kotlin/io/rebble/fossil/di/LibPebbleModule.kt, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, lib/ui/home/tabs/TestTab.dart
This PR adds Dagger and converts most basic flow (sending notifications) to dependency injection. There is still a lot to do, but I feel this is good enough first step to merge it in and continue from there.
Beginning of https://github.com/crc-32/fossil/issues/12
Depends on https://github.com/crc-32/libpebblecommon/pull/1
=> Add dagger and dependency injection

lib/ui/home/tabs/watches_tab.dart, lib/ui/setup/first_run_page.dart, lib/ui/setup/pair_page.dart, test/domain/setup/pair_page_test.dart
If screen is displayed inside tabbed view it needs to use CobbleScaffold.tab, otherwise it needs to use CobbleScaffold.page.
Resolves #100.
=> #100 - Fix a bug where PairPage would use Page scaffold instead of Tab scaffold

android/app/build.gradle
@AliceGrey What do you think of this workaround?
This should only load the ndkPath when environment variable is present. That way we do not annoy any developers in the Android Studio and Github Action still works.
=> only load explicit ndk path if there is environment variable present

lib/ui/home/tabs/watches_tab.dart
Fixes #102
Connecting watch now shows at the top
Removed the text about the background services being stopped
The disconnect button in theory should cancel the current connection process
=> Show connecting watch at the top of the watches page

android/app/src/main/kotlin/io/rebble/cobble/bluetooth/scan/ClassicScanner.kt
This fixes a bug where scan would not emit any data after the scan is complete without any found watches.
=> emit empty device list after classic BT scan is complete

lib/ui/setup/pair_page.dart
Fixes #104
Another way we could do this is save the scanned watches to a temporary list and clear that so we're not clearing the provider. Not sure if there is any downside to just doing it this way though.
=> Search again on pair page should clear previously scanned watches

android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueCommon.kt
If I open the app in emulator, `getDefaultAdapter` returns null. I'm not sure whether this is correct fix or not but if that's correct approach, I'd like to have it merged. I have to include this temp fix in each topic branch I'm working on anyway...
Also fixes #76, unless we wish to do more.
=> Gracefully handle null BluetoothAdapter

android/app/src/main/kotlin/io/rebble/cobble/providers/PebbleKitProvider.kt
it appears Pebble app never did that so we need to to keep doing this for backwards compatibility of all PebbleKit apps
=> do not ever return null tag via PebbleKitProvider

android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/bridges/background/BackgroundAppInstallBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/background/CalendarFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/common/AppInstallFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/ui/BackgroundSetupFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/ui/CalendarControlFlutterBridge.kt, lib/background/main_background.dart, lib/background/modules/apps_background.dart, lib/background/modules/calendar_background.dart, lib/domain/apps/app_manager.dart, lib/domain/apps/requests/app_reorder_request.dart, lib/domain/calendar/requests/delete_all_pins_request.dart, lib/infrastructure/backgroundcomm/BackgroundReceiver.dart, lib/infrastructure/backgroundcomm/BackgroundRpc.dart, lib/infrastructure/backgroundcomm/RpcRequest.dart, lib/infrastructure/backgroundcomm/RpcResult.dart, lib/infrastructure/pigeons/pigeons.g.dart, lib/ui/screens/calendar.dart, lib/util/async_value_extensions.dart, pigeons/pigeons.dart
Until now, to send any commands from UI flutter to background flutter, you had to send a message to the native, which relayed the message to the background.
This was very boilerplate-y and annoying (dealing with pigeon). New system opens direct Send/Receive port between the two with the help of the `IsolateNameServer` and then sends direct objects back and forth.
=> Send UI -> Background messages directly via flutter (no native involved)

images/temp_watch_app.svg, images/temp_watch_face.svg, lang/en.json, lib/domain/entities/hardware_platform.dart, lib/domain/entities/pebble_device.dart, lib/localization/model/model_generator.model.dart, lib/localization/model/model_generator.model.g.dart, lib/ui/common/components/cobble_fab.dart, lib/ui/common/components/cobble_tile.dart, lib/ui/home/home_page.dart, lib/ui/home/tabs/locker_tab.dart, lib/ui/home/tabs/locker_tab/apps_item.dart, lib/ui/home/tabs/locker_tab/apps_sheet.dart, lib/ui/home/tabs/locker_tab/faces_card.dart, lib/ui/home/tabs/locker_tab/faces_sheet.dart, lib/ui/home/tabs/test_tab.dart, lib/ui/router/cobble_scaffold.dart, lib/ui/theme/cobble_theme.dart
Following the mockups, leaving a lot of parts as dead ends, to be implemented later (all should be marked with TODO)
Fix #35 
Depends on https://github.com/pebble-dev/mobile-app/pull/162
=> Add the locker tab

lib/ui/screens/about.dart
The appbar now requires expandedAppBar settings to be set to true in the scenario that previously didn't require it, but about page wasn't updated for that, this fixes it.
=> Fix cut-off appbar in about screen

lib/infrastructure/datasources/preferences.dart, lib/ui/devoptions/dev_options_page.dart
The previous behavior didn't make much sense (it even tried to use a single shared preferences value as both a boolean and a string), and it made it easy to overwrite your rebble token. This PR makes it so that when you call `getBoot()`, the correct boot URL is returned based on the value of `shouldOverrideBoot`, and makes it so that you cannot manually delete the boot URL provided from the Rebble webpage.
=> Fix boot URL override behavior

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/AppDelegate.swift, ios/Runner/bridges/FlutterBridgeSetup.swift, ios/Runner/bridges/background/BackgroundAppInstallFlutterBridge.swift, ios/Runner/bridges/background/FlutterBackgroundController.swift, ios/Runner/bridges/ui/BackgroundSetupFlutterBridge.swift, ios/Runner/bridges/ui/PermissionControlFlutterBridge.swift
This pull request makes the app compile and run after checking out the `ios` branch:
- a reference to a non existing file had to be removed
- the _[PermissionControlFlutterBridge](https://github.com/pebble-dev/mobile-app/commit/699e350d26d79f4ca5b0133aabc1dba695a480ed)_ did not fully conform to _PermissionControl_
- fixes an issue where the Flutter engine is run without knowing the background callback handle
Closes #203
=> iOS: Make current state compile and run

.github/dependabot.yml
This should be reverted when rws branch is merged back into master
=> Set the target branch for dependabot to rws

.github/dependabot.yml
=> Add directory config for github-actions dependabot config

.github/workflows/nightly.yml, .github/workflows/pull-android.yml, .github/workflows/release.yml
The commit https://github.com/pebble-dev/mobile-app/commit/74e174a39732b7e67623f8455a95c6e002e5ffee, set the workflow to grab submodules when checking out the repository, however the `submodules` parameter was specified as an argument to `jobs.build.steps[0]`, rather than `jobs.build.steps[0].with` (why GitHub decided to make their configuration format so confusing is unclear to me). After fixing this, nightlies build again*.
*In that it spits out a debug apk. I have not fixed any analyzer warnings or failing tests.
=> Fix typo in GitHub Actions workflows

android/shared/src/commonMain/kotlin/io/rebble/cobble/shared/handlers/SystemHandler.kt
This is attempt at improving the efficiency and readability of the recently introduced Time Zone truncation code and its accompanying logs. 
The current code in `master` will always be calling `timezone.id.take(MAX_TIMEZONE_NAME_LENGTH)` twice, for all Time Zones:
1. To log the expected output before populating the packet to be sent to the watch
2. When actually populating the packet
The proposed code enforces consistency between the log and the packet sent to the watch, and only does costly String operations when absolutely necessary, by checking the length against the maximum.
=> truncate timezone ID only if it is too long

lib/ui/screens/alerting_app_details.dart
mutedPackages is not mutable, so `.add` fails on a UnmodifiableListMixin exception.
Clone the list and mutate that instead.
=> Fix notification channel muting

android/gradle.properties
Gradle supports [building modules in parallel ](https://docs.gradle.org/current/userguide/performance.html#parallel_execution) as well as avoiding rebuilding modules when nothing in them changes via[ the build cache feature](https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_intro). 
This PR enables both of those features. Right now any improvements from these features is pretty minimal but as the project grows and potentially moduralizes more these provide a large benefit.
=> Enable Gradle Build cache and building modules in parallel

android/gradle.properties
Jetifier is slow ([1](https://developer.android.com/build/optimize-your-build#disable-the-jetifier-flag) & [2](https://adambennett.dev/2020/08/disabling-jetifier/)) and doesn't seem used anymore so this PR just disables it.
=> Disable Jetifier

README.md, android/buildSrc/build.gradle.kts
Instead of adding a manual fix for the Java 21 error, we can just enforce using Java 17 in the build gradle
=> Fix Java 21 issue

test/components/cobble_card_test.dart, test/domain/setup/pair_page_test.dart
I couldn't find anything online like Junits `@Ingore` annotation so I commented out the tests that are consistently failing on CI. If there's a better way to do this let me know 👍
=> Disable currently failing Flutter tests

android/gradle/libs.versions.toml, android/shared/build.gradle.kts, android/shared/src/commonTest/kotlin/io/rebble/cobble/domain/api/AppstoreClientTest.kt
I was trying to add tests for something else but quickly realized I couldn't run `./gradlew test` 😅 
Fixed `Get locker data` in `AppstoreClientTest` by making it a `KoinTest` an providing an instance of `HttpClient` to the Koin DI graph since it's being implicitly depended on in `AppstoreClient`.
=> Fix broken AppstoreClientTest test

android/app/build.gradle.kts, android/gradle/libs.versions.toml, android/pebble_bt_transport/build.gradle.kts, android/shared/build.gradle.kts
I added some dependencies in #320 and noticed some build files used the Version catalog for all dependencies while some didn't. I updated all the build files to consistently use the Version Catalog for declaring and referencing dependencies.
=> Make sure all gradle files are pulling dependencies from the Version Catalog
