android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/io/rebble/fossil/BlueCommon.kt, android/app/src/main/kotlin/io/rebble/fossil/BlueSerial.kt, android/app/src/main/kotlin/io/rebble/fossil/MainActivity.kt, android/app/src/main/kotlin/io/rebble/fossil/WatchService.kt, android/app/src/main/kotlin/io/rebble/fossil/di/AppComponent.kt, android/app/src/main/kotlin/io/rebble/fossil/di/AppModule.kt, android/app/src/main/kotlin/io/rebble/fossil/errors/GlobalErrorHandler.kt, android/app/src/main/kotlin/io/rebble/fossil/notifications/NotificationKey.kt, android/app/src/main/kotlin/io/rebble/fossil/notifications/NotificationListener.kt, android/app/src/main/kotlin/io/rebble/fossil/notifications/NotificationParser.kt, android/app/src/main/kotlin/io/rebble/fossil/notifications/ParsedNotification.kt
Check individual commit messages for more info
=> Refactor notifications & coroutine start 

android/app/build.gradle, android/app/src/main/kotlin/io/rebble/fossil/FossilApplication.kt, android/app/src/main/kotlin/io/rebble/fossil/bluetooth/BlueCommon.kt, android/app/src/main/kotlin/io/rebble/fossil/bluetooth/BlueIO.kt, android/app/src/main/kotlin/io/rebble/fossil/bluetooth/BlueLEDriver.kt, android/app/src/main/kotlin/io/rebble/fossil/bluetooth/classic/BlueSerialDriver.kt, android/app/src/main/kotlin/io/rebble/fossil/bridges/Connection.kt, android/app/src/main/kotlin/io/rebble/fossil/di/AppComponent.kt, android/app/src/main/kotlin/io/rebble/fossil/di/LibPebbleModule.kt, android/app/src/main/kotlin/io/rebble/fossil/di/ServiceModule.kt, android/app/src/main/kotlin/io/rebble/fossil/di/ServiceSubcomponent.kt, android/app/src/main/kotlin/io/rebble/fossil/handlers/AppMessageHandler.kt, android/app/src/main/kotlin/io/rebble/fossil/handlers/PebbleMessageHandler.kt, android/app/src/main/kotlin/io/rebble/fossil/handlers/SystemHandler.kt, android/app/src/main/kotlin/io/rebble/fossil/service/WatchService.kt
Depends on https://github.com/crc-32/libpebblecommon/pull/7
=> Update to new ProtocolHandler, add time sync

lib/ui/home/HomePage.dart, lib/ui/home/tabs/AboutTab.dart, pubspec.yaml
Add basic about tab with url launching and package info.
Meant to fix #42
=> Add about tab

lib/ui/setup/FirstRunPage.dart, lib/ui/setup/PairPage.dart
Skip buttons now send user to /home
=> Make skip buttons work

android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/bridges/Connection.kt, lib/domain/connection/connection_state_provider.dart, lib/infrastructure/pigeons/pigeons.dart, pigeons/pigeons.dart
Flutter now sends start/stop commands to native so it always receives fresh connection status even if tab changes or whole flutter restarts.
=> change connection status to cold stream

android/app/build.gradle, android/app/src/main/kotlin/io/rebble/cobble/bridges/background/TimelineSyncFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/di/AppModule.kt, android/app/src/main/kotlin/io/rebble/cobble/di/LibPebbleModule.kt, android/app/src/main/kotlin/io/rebble/cobble/di/ServiceModule.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/music/ActiveMediaSessionProvider.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/music/MusicHandler.kt, android/app/src/main/kotlin/io/rebble/cobble/notifications/NotificationListener.kt, lib/domain/timeline/timeline_action.g.dart
Fixes #25. PR also includes fixes master branch build (it looks like merge caused errors).
Depends on https://github.com/crc-32/libpebblecommon/pull/13.
=> Music control

lib/domain/connection/pair_provider.dart, lib/domain/connection/scan_provider.dart, lib/infrastructure/datasources/paired_storage.dart, lib/main.dart, lib/ui/home/tabs/test_tab.dart, lib/ui/home/tabs/watches_tab.dart, lib/ui/setup/first_run_page.dart, lib/ui/setup/pair_page.dart, pubspec.lock, pubspec.yaml, test/domain/setup/pair_page_test.dart
=> Add watches page

android/app/src/main/kotlin/io/rebble/cobble/datasources/FlutterPreferences.kt, android/app/src/main/kotlin/io/rebble/cobble/di/AppComponent.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/music/ActiveMediaSessionProvider.kt, android/app/src/main/kotlin/io/rebble/cobble/notifications/NotificationListener.kt, android/app/src/main/kotlin/io/rebble/cobble/service/ServiceLifecycleControl.kt, lib/infrastructure/datasources/preferences.dart, lib/ui/home/tabs/test_tab.dart, pubspec.lock, pubspec.yaml
Fixes functional part of the #22
=> Add option to mute phone sounds when watch is connected 

android/app/build.gradle, android/app/proguard-rules.pro, android/build.gradle, pubspec.lock, pubspec.yaml
Make Google happy ;)
Adds some polish to the fix made by @crc-32 for issue #10
=> Improve release building

.github/workflows/release.yml, .gitignore, android/app/build.gradle
=> Add release building action

lib/ui/home/home_page.dart
=> #106 - Popping route while in tabbed view should try to pop child Navigator first

lib/ui/home/tabs/watches_tab.dart
Taping on the watch row now opens settings
=> Remove hamburger menu icons from myWatches page

lib/ui/setup/pair_page.dart
=> Search again buttons should be hidden when search is in progress

lib/ui/home/tabs/watches_tab.dart
Changed to make the UI clearer.
=> Change All Watches to My Other Watches

pubspec.lock, pubspec.yaml
Not null-safe yet but we're getting there
Fixes #120
=> Upgrade dependencies for flutter 2

android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/CobbleApplication.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/ui/ConnectionUiFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/di/ServiceModule.kt, android/app/src/main/kotlin/io/rebble/cobble/di/ServiceSubcomponent.kt, android/app/src/main/kotlin/io/rebble/cobble/log/FileLoggingTree.kt, android/app/src/main/kotlin/io/rebble/cobble/notifications/NotificationListener.kt, android/app/src/main/kotlin/io/rebble/cobble/service/WatchService.kt, lib/domain/entities/pebble_scan_device.dart, lib/domain/entities/pebble_scan_device.g.dart, lib/infrastructure/datasources/paired_storage.dart, lib/infrastructure/pigeons/pigeons.g.dart, lib/ui/home/tabs/test_tab.dart, lib/ui/home/tabs/watches_tab.dart, lib/ui/router/uri_navigator.dart, lib/ui/screens/install_prompt.dart, lib/ui/setup/pair_page.dart, pigeons/pigeons.dart
See list of commits for full list
=> Fixes for a bunch of reported issues

android/app/src/main/kotlin/io/rebble/cobble/di/AppComponent.kt, android/app/src/main/kotlin/io/rebble/cobble/providers/PebbleKitProvider.kt
this completes part of the #37
=> provide proper firmware version through PebbleKitProvider

README.md, build.yaml, lang/readme.md, lib/localization/localization_delegate.dart, lib/localization/model/model_generator.dart
As requested in https://github.com/pebble-dev/mobile-app/pull/117#issuecomment-812358341.
=> #61 - Update README.md with information about localization.

android/app/src/main/kotlin/io/rebble/cobble/CobbleApplication.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueGATTServer.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueLEDriver.kt
Mild refactor using actor instead of a looping thread, much nicer on performance
=> Ble cleanup/refactor

android/app/build.gradle, android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/bridges/background/BackgroundAppInstallBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/background/FlutterBackgroundController.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/common/AppInstallFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/di/BackgroundFlutterModule.kt, android/app/src/main/kotlin/io/rebble/cobble/di/BackgroundFlutterSubcomponent.kt, android/app/src/main/kotlin/io/rebble/cobble/di/LibPebbleModule.kt, lang/en.json, lib/background/modules/apps_background.dart, lib/domain/apps/app_manager.dart, lib/domain/apps/default_apps.dart, lib/domain/db/cobble_database.dart, lib/domain/db/dao/app_dao.dart, lib/domain/db/models/app.dart, lib/domain/db/models/app.g.dart, lib/domain/timeline/watch_apps_syncer.dart, lib/domain/timeline/watch_timeline_syncer.dart, lib/infrastructure/datasources/preferences.dart, lib/infrastructure/pigeons/pigeons.g.dart, lib/localization/model/model_generator.model.dart, lib/localization/model/model_generator.model.g.dart, lib/ui/home/tabs/test_tab.dart, pigeons/pigeons.dart, pubspec.yaml
This PR adds the ability to change the order in which apps appear in the menu.
It also fixes annoying bug where Flutter background logic would stop working after every Flutter hot restart.
Depends on the https://github.com/pebble-dev/libpebblecommon/pull/18
=> App reordering

android/app/src/main/kotlin/io/rebble/cobble/bridges/background/FlutterBackgroundController.kt, lib/background/main_background.dart, lib/localization/localization.dart, lib/main.dart
this fixes the issue where calendar sync stopped working since localization update
=> Fix calendar sync not working

android/app/build.gradle, android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/bridges/common/ScreenshotsFlutterBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/di/LibPebbleModule.kt, android/app/src/main/kotlin/io/rebble/cobble/di/bridges/CommonBridgesModule.kt, lib/infrastructure/pigeons/pigeons.g.dart, lib/ui/home/tabs/test_tab.dart, pigeons/pigeons.dart, pubspec.lock, pubspec.yaml
Added ability to take a screenshot of a watch and save it to a phone.
Depends on https://github.com/pebble-dev/libpebblecommon/pull/20
=> Screenshot downloading

android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueGATTServer.kt, android/app/src/main/kotlin/io/rebble/cobble/datasources/WatchMetadataStore.kt, android/app/src/main/kotlin/io/rebble/cobble/di/ServiceModule.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/AppMessageHandler.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/AppRunStateHandler.kt, android/app/src/main/kotlin/io/rebble/cobble/handlers/SystemHandler.kt, lib/background/main_background.dart, lib/background/modules/apps_background.dart, lib/background/modules/calendar_background.dart, lib/ui/home/tabs/watches_tab.dart
See commit names for full list
=> Couple of miscelaneous fixes and improvements

.fvm/fvm_config.json, .github/workflows/nightly.yml, .github/workflows/release.yml, .gitignore, README.md, pubspec.lock, pubspec.yaml
this should help with builds randomly starting to fail when flutter upgrades
=> freeze flutter versions and add fvm support

lib/ui/theme/cobble_theme.dart
This should fix #119, though I'm not sure it will work on iOS
=> Fix the statusbar color

lang/en.json, lib/localization/model/model_generator.model.dart, lib/localization/model/model_generator.model.g.dart, lib/ui/common/components/cobble_tile.dart, lib/ui/common/icons/back_comp_icon.dart, lib/ui/router/cobble_scaffold.dart, lib/ui/screens/about.dart, lib/ui/screens/settings.dart
Fixes #42
~~Though it doesn't currently build because of the missing icons upstream, still working on that~~ Depends on https://github.com/pebble-dev/mobile-app/pull/162
=> Add the about page

lang/en.json, lib/ui/screens/alerting_apps.dart, lib/ui/screens/notifications.dart
This requires testing, but it should fix the situation mentioned in #125
=> Use a builder with app selector and misc fixes

lib/ui/common/components/cobble_button.dart, lib/ui/common/components/cobble_fab.dart
A small fix to make the icon sizes consistent with the mockups
=> Fix the button icon sizes

lang/en.json, lib/domain/calendar/calendar_list.dart, lib/domain/calendar/selectable_calendar.dart, lib/localization/model/model_generator.model.dart, lib/localization/model/model_generator.model.g.dart, lib/ui/common/components/cobble_tile.dart, lib/ui/home/tabs/test_tab.dart, lib/ui/screens/calendar.dart, lib/ui/screens/settings.dart
Also from the mockups, fully functional, just taken away from the test tab
=> Set up the calendar page

android/app/src/androidTest/kotlin/io/rebble/cobble/bluetooth/BlueGATTServerTest.kt, android/app/src/main/java/io/rebble/cobble/pigeons/Pigeons.java, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueCommon.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueGATTServer.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/BlueLEDriver.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/ProtocolIO.kt, android/app/src/main/kotlin/io/rebble/cobble/bluetooth/classic/BlueSerialDriver.kt, android/app/src/main/kotlin/io/rebble/cobble/bridges/common/RawIncomingPacketsBridge.kt, android/app/src/main/kotlin/io/rebble/cobble/datasources/IncomingPacketsListener.kt, android/app/src/main/kotlin/io/rebble/cobble/di/bridges/CommonBridgesModule.kt, lib/domain/connection/raw_incoming_packets_provider.dart, lib/infrastructure/datasources/dev_connection.dart, lib/infrastructure/datasources/preferences.dart, lib/infrastructure/pigeons/pigeons.g.dart, lib/ui/devoptions/dev_options_page.dart, pigeons/pigeons.dart
With this PR, `pebble ping` and `pebble logs` commands should work through developer connection
This completes part of the https://github.com/pebble-dev/mobile-app/issues/47
=> Send watch packets via developer connection

android/app/src/main/kotlin/io/rebble/cobble/handlers/AppMessageHandler.kt
This fixes https://github.com/pebble-dev/mobile-app/issues/37
=> send connect and disconnect AppMessage intents

android/app/src/main/kotlin/io/rebble/cobble/bridges/common/AppInstallFlutterBridge.kt, lib/domain/apps/app_manager.dart, lib/infrastructure/datasources/dev_connection.dart
This completes part of the https://github.com/pebble-dev/mobile-app/issues/47
=> add "pebble install" support to developer connection

android/app/build.gradle, android/app/src/main/kotlin/io/rebble/cobble/handlers/AppMessageHandler.kt, android/app/src/main/kotlin/io/rebble/cobble/util/Intent.kt
Depends on the https://github.com/pebble-dev/libpebblecommon/pull/24/files
=> add sports/golf app customization

README.md
These instructions got me from an Ubuntu laptop with no Android or Flutter environment on it to a working build of Cobble.
=> README: add getting started instructions for building on Ubuntu

ios/Podfile.lock, ios/Runner/Pigeon/PigeonsAlias.h, ios/Runner/bridges/common/AppInstallControlFlutterBridge.swift, ios/Runner/bridges/common/ScanFlutterBridge.swift, lib/infrastructure/pigeons/pigeons.g.dart
Thanks for merging the `ios` branch back to `master` - that's great!
Unfortunately the latest state is not compiling. I have had a look and think I got the issues fixed + corrected a warning. These are the changes.
=> Make iOS target compile

lib/ui/home/tabs/watches_tab.dart
Picking up where https://github.com/pebble-dev/mobile-app/pull/164 left off
=> Use cobble theming in the watches tab

lib/ui/common/components/cobble_tile.dart, lib/ui/common/icons/system_app_icon.dart, lib/ui/home/tabs/locker_tab/apps_item.dart, lib/ui/home/tabs/locker_tab/apps_sheet.dart
Preliminary support for system app icons, for other kinds of icons we have images fetched from the app metadata, so we need to handle those another way
=> Add system apps icons

lib/ui/home/tabs/test_tab.dart, lib/ui/screens/about.dart, lib/ui/screens/install_prompt.dart, lib/ui/setup/boot/rebble_setup.dart, lib/ui/test/test_page.dart
Seems that RaisedButton is deprecated, we may as well use CobbleButton instead
=> Use CobbleButton instead of RaisedButton

.github/workflows/nightly.yml, .github/workflows/pull-android.yml, .github/workflows/release.yml
This PR:
- Changes all actions to use hosted runners
- Upgraded to setup-dart@1.3 for all actions
- Upgraded to ubuntu-latest for all actions
- Added a `workflow_dispatch` trigger on Android Nightly
- Temporarily added continue on error blocks to `analyze`
=> Fix Actions Workflows

lib/domain/timeline/watch_apps_syncer.dart
I made a mistake in the previous PR and introduced this regression, let's fix it
=> Fix broken app sync to the watch

lib/domain/apps/requests/app_reorder_request.dart, lib/domain/apps/requests/force_refresh_request.dart, lib/infrastructure/backgroundcomm/BackgroundReceiver.dart, lib/infrastructure/backgroundcomm/BackgroundRpc.dart, lib/infrastructure/backgroundcomm/RpcRequest.dart, lib/infrastructure/backgroundcomm/RpcResult.dart
This introduces some methods to turn objects that get sent between the background thread and the ui into maps
=> Fix the communication between the app and the background

android/app/proguard-rules.pro, android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml
This also fixes issues with the calendar in proguard
=> Add network permissions for locker and store

lib/background/actions/calendar_action_handler.dart, lib/background/main_background.dart, lib/domain/api/appstore/appstore.dart, lib/domain/api/auth/auth.dart, lib/domain/api/boot/boot.dart, lib/domain/calendar/calendar_list.dart, lib/domain/calendar/calendar_syncer.db.dart, lib/domain/timeline/watch_timeline_syncer.dart, lib/infrastructure/backgroundcomm/BackgroundRpc.dart, lib/infrastructure/datasources/workarounds.dart, lib/ui/devoptions/debug_options_page.dart, lib/ui/home/tabs/test_tab.dart, lib/ui/screens/alerting_app_details.dart, lib/ui/screens/alerting_apps.dart, lib/ui/screens/calendar.dart, lib/ui/screens/notifications.dart, lib/ui/setup/boot/rebble_setup_fail.dart, lib/ui/setup/pair_page.dart, lib/ui/splash/splash_page.dart, pubspec.lock, pubspec.yaml
Depends on #243 
Finishes the update of riverpod
=> Update riverpod to the latest version

.github/workflows/nightly.yml, .github/workflows/pull-android.yml
=> Ignore no golden failures existing

.github/workflows/nightly.yml, .github/workflows/pull-android.yml, .github/workflows/release.yml
Since the required java version was bumped
=> Update CI to newer java version and to pass

README.md
Was trying to set the project up and got a 404 for the original link didn't work
=> Fix FVM link in README

android/shared/build.gradle.kts, android/shared/src/commonMain/kotlin/io/rebble/cobble/shared/ui/view/home/locker/LockerAppList.kt, android/shared/src/commonMain/kotlin/io/rebble/cobble/shared/ui/view/home/locker/LockerItemSheet.kt
I hit this a bit in #331 and saw some discussion around it on Discord so just blanket adding opt in for some the experimental compose APIs
=> Opt in to experimental Compose APIs to avoid confusion

android/app/src/main/AndroidManifest.xml
=> Fix warning on Startup
